version: 2
jobs:
  docs-build:
    docker:
      - image: circleci/python:3.6-stretch
    steps:
      - checkout
      - run: 
          name: prep environment & make docs
          command: |
            python3 -m venv test-env
            . test-env/bin/activate
            pip install sphinx sphinx_rtd_theme --progress-bar off
            cd doc
            make html
      - persist_to_workspace: # save contents of doc/_build to intermediate location accesible to later jobs
          root: doc/_build 
          paths: html
  docs-deploy:
    docker:
      - image: node:8.10.0  # use node base image so `npm` package avail
    steps:
      - checkout
      - attach_workspace:
          at: doc/_build # mounts the doc/_build dir
      - run:
          name: Disable jekyll builds
          command: touch doc/_build/html/.nojekyll
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "jliu176@gmail.com"
            git config user.name "ci-build"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --dist doc/_build/html
      - add_ssh_keys:
          fingerprints:
            - "46:f5:3e:22:e2:fb:5f:2d:da:38:06:e7:ad:0f:92:a5"
      - run:
          name: Deploy docs to gh-pages branch
          # skip CI
          command: gh-pages --dotfiles --message "[skip ci] Updates" --dist doc/_build/html
workflows:
  version: 2
  build:
    jobs:
      - docs-build
      - docs-deploy:
          requires:
            - docs-build
          filters:
            branches:
              only: master